#!/usr/bin/env python3
# Section 8: the PDF's Word Groups, rebuilt for memory. Word lists are faithful to the
# source (OCR fixed); theme / best-SE-pairing / hook are added study scaffolding.
# Each tuple: (GROUP, theme, words, antonyms_or_None, se_pair, hook)

G = [
("HARSH / BITING / SHARP","of speech or wit — cutting",
 "acerbic, acrimonious, caustic, incisive, scathing, trenchant",None,
 "caustic ≈ scathing","All describe a *tongue*: trenchant/incisive cut cleanly; acrimonious adds bitterness."),
("NOT THOROUGH","done superficially",
 "cursory, perfunctory, summarily, superficial",None,
 "cursory ≈ perfunctory","A *cursor* skims the surface → cursory glance, perfunctory effort."),
("HINT / INDIRECT REFERENCE","saying without stating",
 "allude/allusion, cue, implicit, innuendo, insinuate, tacit",
 "blatant, explicit, patent",
 "implicit ≈ tacit","Tacit = unspoken-but-understood; antonyms shout it (blatant/patent)."),
("CONFIRM / SUPPORT (a claim)","back with evidence",
 "affirm, clinch, corroborate, endorse, ratify, substantiate, testify, validate",
 "unfounded",
 "corroborate ≈ substantiate","Evidence words — see §5.13. Antonym 'unfounded' = unsupported."),
("STRENGTHEN / SUPPORT (a thing)","prop up, reinforce",
 "bastion, bolster, buttress, fortify, prime, prop",None,
 "bolster ≈ buttress","A buttress braces a wall; bolster braces morale."),
("VARIETY","made of many kinds",
 "diversity, eclectic, motley, multifaceted, multifarious, sundry, variegate, versatile",None,
 "multifarious ≈ sundry","Eclectic = drawn from many sources; motley = mismatched mix."),
("BAN","officially forbid",
 "interdict, sanction, veto",None,
 "interdict ≈ veto","⚠ **sanction** is auto-antonym: here it = *forbid*, elsewhere = *approve*."),
("CAN'T DECIDE / CHANGEABLE","unsteady, inconsistent",
 "arbitrary, capricious, erratic, inconsistent, irresolute, mercurial, oscillate, sway, temperamental, vacillate, volatile, waffle, waver, whimsical, fluctuating",None,
 "vacillate ≈ waver","Mercurial/capricious/volatile = mood swings; vacillate/waver = can't choose."),
("TO BLAME / ACCUSE","charge with wrongdoing",
 "allege, implicate, impute, incriminate, indict, recriminate",None,
 "incriminate ≈ implicate","Indict = formally charge; impute = attribute fault to."),
("FREE FROM BLAME","clear of guilt",
 "absolve, acquit, exculpate, exonerate, vindicate",None,
 "exonerate ≈ exculpate","ex- = OUT of blame. Direct antonyms of the 'TO BLAME' set above."),
("PLACE SIDE BY SIDE","adjoining",
 "abut, adjacent, contiguous, juxtaposition",None,
 "abut ≈ contiguous","Properties that abut are contiguous; juxtapose = set side by side to compare."),
("WITHOUT REAL POWER","in name only",
 "figurehead, nominal, titular",None,
 "nominal ≈ titular","A titular head is a figurehead — title without authority."),
("DISRESPECTING SACRED THINGS","irreverence toward the holy",
 "blasphemy, desecrate, impious, profane, sacrilege",
 "consecrate",
 "desecrate ≈ profane","Profane/desecrate a temple; consecrate makes it holy again."),
("CARELESS / DIRTY","untidy",
 "disheveled, rumpled, shabby, sloppy, slovenly, unkempt",None,
 "disheveled ≈ unkempt","Slovenly = habitually messy; rumpled = wrinkled."),
("USED TO / HARDENED","accustomed",
 "habituate, immune, inure, inveterate",None,
 "habituate ≈ inure","Inure = toughen by exposure; inveterate = deep-rooted by long habit."),
("UNDERSTAND","grasp fully",
 "apprehend, assimilate, comprehend, fathom, intelligible",
 "illegible",
 "comprehend ≈ apprehend","Fathom = get to the bottom of; intelligible = able to be grasped."),
("IMPURE / POISONOUS","contaminated or harmful",
 "adulterate, contaminate, noxious, toxic, vitiate",None,
 "adulterate ≈ vitiate","Vitiate/adulterate = spoil by adding something inferior."),
("BEST EXAMPLE / IDEAL","the perfect model",
 "apotheosis, archetype, embody, epitome, exemplify, paradigm, paragon, personify",None,
 "epitome ≈ paragon","Archetype/paradigm = the original pattern; paragon = a model of excellence."),
("BEG / ENTREAT","plead earnestly",
 "behest, beseech, entreaty, implore, importune, supplicate",None,
 "beseech ≈ implore","Importune = pester with requests; behest = a command/urging."),
("PERSUADE / URGE","move someone to act",
 "cajole, coax, cogent, enjoin, exhort, hortatory, induce, urge, wheedle",None,
 "exhort ≈ enjoin","Cajole/coax/wheedle = sweet-talk; cogent/hortatory = persuasive in argument."),
("INTELLIGENT / WISE","mentally sharp",
 "acuity, acumen, astute, discerning, discriminating, insightful, judicious, perceptive, perspicacious, prudent, sagacious, sage, savant",None,
 "perspicacious ≈ sagacious","See §4.6. Judicious/prudent = wise *and cautious*."),
("STUPID / FOOLISH","lacking sense",
 "asinine, fatuous, imbecile, inane, oafish, obtuse",None,
 "fatuous ≈ inane","Obtuse = slow to get it; the rest = silly/empty. See §4.7."),
("TEMPT / PLOT / TRICK","scheme or lure",
 "allure, beguile, collude, connive, conspire, entice, lure, ploy, ruse, scheme, tactic",None,
 "ploy ≈ ruse","collude/connive/conspire = plot together; allure/entice/beguile = draw in."),
("CAREFUL / PRECISE","attentive to detail",
 "conscientious, fastidious, meticulous, nice, punctilious, purist, scrupulous",None,
 "meticulous ≈ punctilious","⚠ **nice** here = *precise/exacting* (old sense). Fastidious can shade into fussy."),
("SULKING / BAD-TEMPERED","gloomily ill-humored",
 "dour, morose, peevish, petulant, pout, saturnine, sullen, surly",None,
 "morose ≈ saturnine","Petulant/peevish = childishly irritable; saturnine/dour = grimly gloomy."),
("FALSEHOOD","lying",
 "mendacity, perjury, prevarication",
 "veracity",
 "mendacity ≈ prevarication","Perjury = lying under oath. Antonym veracity = truthfulness."),
("ILLOGICAL / STRANGE","absurdly odd",
 "absurd, atypical, bizarre, ludicrous, outlandish, preposterous, uncanny",None,
 "ludicrous ≈ preposterous","Uncanny = eerily strange; outlandish = bizarrely unfamiliar."),
("PUZZLING","hard to figure out",
 "conundrum, cryptic, enigma, garble, inscrutable, intrigue, labyrinth, maze",None,
 "cryptic ≈ inscrutable","conundrum/enigma = the puzzle; garble = jumble a message. See §4.19."),
("FEARFUL / LACKING COURAGE","timid or cowardly",
 "cower, craven, cringe, daunt, flinch, petrify, pusillanimous, trepidation",None,
 "craven ≈ pusillanimous","cower/cringe/flinch = shrink back; trepidation = dread. See §4.18."),
("TO IRRITATE / MAKE ANGRY","annoy or enrage",
 "disgruntle, exasperate, grate, harangue, heckle, indignation, infuriate, irksome, miffed, nag, nettle, peeve, pique, vex",None,
 "nettle ≈ vex","Exasperate/infuriate = strongly anger; nettle/vex/peeve = mildly irritate."),
("BRAVE","fearless",
 "audacious, chivalry, dauntless, gallant, intrepid, pluck, undaunted, valiant, valor",None,
 "intrepid ≈ dauntless","Audacious adds boldness/nerve. Antonym set = the 'FEARFUL' group."),
("ACCUSE / DEFAME","attack a reputation",
 "aspersion, calumny, defame, libel, malign, obloquy, opprobrium, slander, slur, stigmatization, vilify",None,
 "calumny ≈ aspersion","libel = written, slander = spoken; obloquy/opprobrium = public disgrace."),
("RESPECT / REVERE","honor deeply",
 "commemorate, deference, exalt, hallow, homage, revere, venerate",None,
 "revere ≈ venerate","Hallow = make holy; deference = respectful yielding."),
("LACK OF RESPECT / NERVE","brazen rudeness",
 "audacious, brazen, cheeky, effrontery, gall, impertinent, impudent, insolent, nerve, presumptuous, temerity",None,
 "effrontery ≈ temerity","gall/nerve/effrontery = shameless boldness; impudent/insolent = disrespectful."),
("FAKE / FALSE / DOUBTFUL","not genuine",
 "apocryphal, dubious, erroneous, ersatz, fabricate, fallacious, illicit, phony, sham, sophistry, specious, spurious",None,
 "specious ≈ spurious","ersatz/sham = fake substitute; apocryphal = of doubtful authenticity. See §4.4."),
("GIVE UP / RENOUNCE","formally surrender",
 "abdicate, abjure, abnegate, cede, forgo, forsake, forswear, relinquish, renounce",None,
 "relinquish ≈ renounce","abjure/forswear = renounce on oath; abdicate = give up a throne."),
("CREDULITY / TRUST (without deception)","trusting, easily fooled",
 "artless, credence, credible, credulous, dupe, guileless, gullible, ingenuous, naïve, naiveté",None,
 "credulous ≈ gullible","⚠ credulous = *too trusting*; credible = *believable* — opposite roles, same root (cred-)."),
("FUSSY","over-particular",
 "finicky, nitpicking, persnickety, squeamish, stickler",None,
 "finicky ≈ persnickety","A stickler insists on details; squeamish = easily disgusted."),
("SECRET / STEALTHY","done in hiding",
 "clandestine, covert, furtive, oblique, skulk, sly, stealth, surreptitious",
 "overt",
 "clandestine ≈ surreptitious","furtive = shifty/sneaky; antonym overt = out in the open."),
("HIDE / DISGUISE","conceal the true form",
 "camouflage, cloak, dissemble, feign, guise, incognito, mask, masquerade, shroud, veneer",None,
 "dissemble ≈ feign","dissemble = hide feelings; veneer = a thin false surface."),
("OVERLY PROUD / ARROGANT","puffed up",
 "arrogant, bombastic, braggart, bravado, conceited, egotistical, haughty, hubris, pompous, supercilious, swagger, vainglorious",None,
 "haughty ≈ supercilious","bombastic/pompous = inflated speech; hubris = fatal pride. See §4.17."),
("SPEAK LESS / BRIEF","using few words",
 "abbreviated, abridge, brevity, condense, laconic, monosyllabic, pithy, reticent, succinct, taciturn",None,
 "laconic ≈ taciturn","pithy/succinct = brief *and* meaty; reticent/taciturn = disinclined to speak. See §4.11."),
("IRRITABLE","quick to anger",
 "cantankerous, chagrin, choleric, churlish, curmudgeon, grouchy, gruff, irascible, testy",None,
 "irascible ≈ testy","choleric/irascible = hot-tempered; a curmudgeon is a grumpy old grouch."),
("CHEAT / DECEIVE","mislead for gain",
 "artful, artifice, bilk, chicanery, crafty, duplicity, dupe, fleece, guile, guileful, hoodwink, mislead, swindle, wily",None,
 "bilk ≈ fleece","duplicity/guile/chicanery = the trait; bilk/fleece/swindle = the act. See §4.4."),
("TO GUESS / INFER","conclude from clues",
 "conjecture, construe, deduce, extrapolate, surmise",None,
 "conjecture ≈ surmise","extrapolate = project beyond known data; construe = interpret."),
("ACT PROPERLY","fitting, decorous",
 "decorous, demure, prim, propriety, seemly",
 "execrable, flagrant, malfeasance, unbecoming",
 "decorous ≈ seemly","propriety = correct behavior; antonyms = flagrant/unbecoming misconduct."),
("TALKATIVE","wordy in speech",
 "garrulous, long-winded, loquacious, prolix, verbiage, verbose, voluble",None,
 "garrulous ≈ loquacious","prolix/verbose = tediously wordy (esp. writing). See §4.11."),
("WITHOUT MISTAKE / FLAWLESS","beyond fault",
 "perfect, flawless, immaculate, impeccable, infallible, integrity, irreproachable, probity, rectitude, unimpeachable",None,
 "impeccable ≈ irreproachable","probity/rectitude/integrity = moral flawlessness; impeccable = without flaw."),
("STRANGE / QUIRKY","peculiar to a person",
 "eccentric, foible, idiosyncrasy, quirkiness",None,
 "foible ≈ idiosyncrasy","A foible = a minor personal weakness/oddity."),
("DISLOYALTY","betrayal",
 "betray, insidious, perfidy",
 "fealty, fidelity",
 "perfidy ≈ treachery","insidious = treacherous in a sneaky way; antonyms fealty/fidelity = loyalty."),
("THRIVING / REVIVE","flourish or come back to life",
 "burgeon, regenerate, rejuvenate, resuscitation, revive",None,
 "rejuvenate ≈ regenerate","burgeon = grow rapidly (links to INCREASE, §4.9)."),
("CLEAR / EASY TO UNDERSTAND","transparent",
 "clarity, elucidate, exposition, expound, limpid, lucid, pellucid",None,
 "lucid ≈ pellucid","elucidate/expound = to make clear. Antonyms = the obscure groups. See §4.12."),
("SUPPORTER","one who backs",
 "advocate, ally, champion, endorse, espouse, lobbyist, proponent, protagonist, tout",
 "adversary, antagonist, detractor, foe, impugn, inimical, nemesis, opponent",
 "proponent ≈ advocate","espouse/champion = to support a cause; antonym set = enemies/opponents."),
("FEELING GUILTY / SORRY","remorseful",
 "contrite, penitent, remorse, rueful",None,
 "contrite ≈ penitent","rueful = regretful; contrite = sincerely repentant."),
("SHOW-OFF","flashy display",
 "flamboyance, flaunt, grandiloquent, grandiose, ostentatious, pretentious",None,
 "ostentatious ≈ pretentious","grandiloquent/grandiose = pompously grand; flaunt = parade it."),
("IMMORAL / CORRUPT","morally degraded",
 "debauchery, decadent, degenerate, depravity, dissolute, improbity, wayward",None,
 "depravity ≈ debauchery","dissolute/decadent = self-indulgent; improbity = lack of integrity."),
("GAP / PAUSE","a break in continuity",
 "abeyance, hiatus, lull, moratorium, respite",None,
 "hiatus ≈ respite","abeyance = temporarily suspended; moratorium = an official halt."),
("UNCLEAR / HAZY","indistinct",
 "amorphous, becloud, cloud, indistinct, murky, nebulous",None,
 "nebulous ≈ amorphous","becloud = to make hazy; amorphous = shapeless. See §4.12."),
("LOSE STRENGTH / WEAKEN","grow feeble",
 "atrophy, attenuate, attrition, debilitate, degenerate, degradation, effete, enervate, enfeeble, wilt, wither, flagging, sap",None,
 "enervate ≈ debilitate","⚠ enervate = *weaken* (not energize!). See §4.9 & §5.3."),
("TO DISPROVE","refute or expose",
 "belie, debunk, discredit, expostulate, rebut, refute, remonstrate",None,
 "refute ≈ rebut","belie/debunk = expose as false; remonstrate/expostulate = protest against."),
("CORRECT / REPAIR / ATONE","make right",
 "amend, atone, disabuse, expiate, indemnify, redemption, redress, reparation, restitution",None,
 "redress ≈ reparation","expiate/atone = pay for a wrong; disabuse = free from error."),
("DETERMINED / PERSISTENT","unyielding in effort",
 "resolute, dogged, endure, immutable, indefatigable, persevere, persistence, steadfast, tenacious",None,
 "tenacious ≈ dogged","indefatigable = tireless; steadfast/resolute = firm in purpose."),
("EXCESSIVE PATRIOTISM","blind devotion to a group",
 "chauvinism, fanatic, jingoism, zealot",None,
 "chauvinism ≈ jingoism","jingoism = aggressive nationalism; zealot = fanatical adherent."),
("PLANNED / DELIBERATE","done on purpose",
 "calculated, deliberate, forethought, intentional, premeditated, studied",
 "extemporaneous, impetuous, impromptu, improvise, offhand",
 "premeditated ≈ calculated","Antonyms = unplanned/impromptu; impetuous = acting on impulse."),
("LUCKY / FAVORABLE","by good fortune",
 "fortuitous, opportune, propitious, serendipity",
 "despair, hapless, wretched",
 "propitious ≈ opportune","serendipity = lucky discovery; hapless = unlucky."),
("UNWILLING TO SPEND / STINGY","tight with money",
 "closefisted, miserly, niggardly, parsimonious, skinflint, stingy, stint, tightfisted",None,
 "parsimonious ≈ miserly","See §4.14 (contrast virtuous thrift vs. stinginess)."),
("LACKING ENERGY / LAZY","sluggish, listless",
 "indolent, jaded, lackadaisical, lackluster, languid, lassitude, lethargic, listless, sloth, sluggish, torpor, torpid",None,
 "lethargic ≈ torpid","lassitude/torpor = the *state* of weariness; indolent = habitually lazy."),
("STUBBORN","refusing to yield",
 "adamant, defiant, incorrigible, intractable, intransigent, obdurate, obstinate, pertinacious, perverse, recalcitrant, refractory, willful",None,
 "intransigent ≈ obdurate","intractable/recalcitrant = resistant to control. See §4.16 & §5.7."),
("SURE / CERTAIN","beyond doubt",
 "certain, absolute, categorical, certitude, conviction, emphatic, incontrovertible, unqualified",
 "contingent, provisional, qualify, tentative",
 "categorical ≈ unequivocal","Antonyms = tentative/provisional. See §4.13."),
("CANCEL / REVOKE","make void",
 "annul, disavow, gainsay, null, recant, renege, repeal, repudiate, rescind, retract, revoke, void",None,
 "rescind ≈ revoke","recant/retract = take back a statement; repudiate = reject/disown."),
("RELEVANT","to the point",
 "apposite, apropos, germane, pertinent",None,
 "germane ≈ pertinent","apposite/apropos = strikingly relevant. Antonym: extraneous."),
("SAD / GLOOMY","sorrowful",
 "anguish, bereaved, bleak, crestfallen, dejected, desolate, despondent, forlorn, glum, lament, lugubrious, melancholy, plaintive, woe",None,
 "despondent ≈ dejected","lugubrious = exaggeratedly mournful; plaintive = sounding sad."),
("HARD-WORKING / DILIGENT","industrious",
 "assiduous, diligent, industrious, painstaking, sedulous, toil, meticulous, punctilious, exacting",None,
 "assiduous ≈ sedulous","painstaking/meticulous = careful and thorough."),
("GREED","craving more",
 "avarice, covetous, cupidity, gluttony, rapacious, ravenous, voracious",None,
 "rapacious ≈ voracious","avarice/cupidity = greed for money; voracious/ravenous = for food (or anything)."),
("UNCLEAR IN MEANING","open to interpretation",
 "ambivalent, ambiguous, equivocal",None,
 "ambiguous ≈ equivocal","⚠ ambivalent = mixed *feelings* (people); ambiguous = double *meaning* (statements). See §4.13."),
("CALM DOWN / SOOTHE","reduce intensity",
 "allay, alleviate, ameliorate, appease, assuage, conciliate, extenuating, mitigate, mollify, pacify, placate, propitiate, solace, temper",
 "exacerbate",
 "assuage ≈ mitigate","mollify/placate/appease = calm a *person*; antonym exacerbate = worsen. See §5.5."),
("ORDINARY / DULL","commonplace, unoriginal",
 "banal, cliche, commonplace, derivative, hackney, humdrum, mundane, pedestrian, platitude, plebeian, quotidian, trite, unremarkable",None,
 "banal ≈ trite","pedestrian/prosaic = dull; quotidian = everyday; a platitude = a trite remark."),
("SPLIT / DIVISION","a gap or break",
 "chasm, dichotomy, gulf, rift, schism",None,
 "rift ≈ schism","schism = a formal split (esp. in a group); dichotomy = a division into two."),
("INCLINATION / TENDENCY","a leaning toward",
 "affinity, aptitude, bent, disposed, penchant, predilection, predisposition, proclivity, propensity",None,
 "penchant ≈ propensity","proclivity/predilection = a strong preference; aptitude = natural ability."),
("SHORT-LIVED","lasting briefly",
 "ephemeral, evanescent, fleeting, transient, transitory, momentary",None,
 "ephemeral ≈ transient","See §4.20 & §5.9. Antonyms: enduring/permanent."),
("DIFFICULT TO UNDERSTAND","obscure, deep",
 "abstract, abstruse, arcane, esoteric, mystical, obscure, occult, profound, profundity, recondite, enigmatic, inscrutable, unintelligible",
 "perspicuous",
 "abstruse ≈ recondite","esoteric/arcane = known to few; antonym perspicuous = clearly expressed. See §4.12."),
("DISTURBED / AGITATED","unsettled",
 "consternation, disconcert, dismay, disquiet, distraught, faze, fluster, foment, frenetic, hysterical, implacable, overwrought, perturb",None,
 "perturb ≈ disconcert","foment = stir up (active); see §4.8 & §5.19."),
("HAPPY / JOYFUL","full of delight",
 "beam, ecstasy, elated, euphoria, exhilaration, exultant, felicity, gaiety, jest, jocular, jocund, jollity, jovial, jubilant, rapturous, regale, uproarious",None,
 "elated ≈ jubilant","jocular/jocund/jovial = merry in manner; euphoria/ecstasy = intense joy."),
("AGGRESSIVE / ARGUMENTATIVE","spoiling for a fight",
 "bellicose, belligerent, contentious, disputatious, fractious, hostility, litigious, polemical, pugnacious, truculent",None,
 "bellicose ≈ belligerent","pugnacious/truculent = combative; litigious = quick to sue; polemical = controversial."),
("AWKWARD / CLUMSY","ungraceful",
 "fumble, gauche, gawky, ungainly, clumsy",
 "urbane, suave",
 "gauche ≈ ungainly","gauche = socially clumsy; antonyms urbane/suave = polished."),
("EXCESSIVE FLATTERY","servile praise",
 "fawn, fulsome, obsequious, sycophant",None,
 "obsequious ≈ sycophantic","⚠ fulsome = *disgustingly* excessive. See §4.3 & §5.17."),
("DOMINATING / TYRANNICAL","ruling absolutely",
 "absolute, authoritative, autocrat, despot, doctrinaire, dogmatic, hegemony, imperious, martinet, totalitarian, tyrant",None,
 "autocrat ≈ despot","martinet = a strict disciplinarian; doctrinaire/dogmatic = rigidly opinionated."),
("PARTIAL / BIASED","prejudiced",
 "subjective, bigot, discriminatory, partisan, prejudiced",
 "dispassionate, egalitarian, equitable, evenhanded, objectivity, disinterested",
 "partisan ≈ partial","⚠ antonym **disinterested** = *unbiased* (not 'bored'). See §7 #34."),
("CALM / COMPOSED","unshaken in temperament",
 "aplomb, composure, equanimity, impassive, imperturbable, nonchalant, phlegmatic, placid, serene, staid, stolid, tranquil",None,
 "equanimity ≈ aplomb","phlegmatic/stolid/impassive = unemotional by nature. See §4.8 & §5.11."),
("DISAPPROVE / CONDEMN","attack verbally",
 "assail, berate, castigate, decry, denounce, denunciation, diatribe, epithet, excoriate, fulminate, invective, lambaste, rant, revile, rile, tirade, upbraid, vituperative",None,
 "castigate ≈ excoriate","diatribe/tirade/invective = the angry *speech*. See §4.2 & §5.2."),
("CAUTIOUS / WARY","carefully guarded",
 "chary, circumspect, gingerly, heedful, leery, prudent, wary",
 "daredevil, folly, foolhardy, rash, reckless",
 "chary ≈ wary","circumspect = looking around before acting; antonyms = rash/foolhardy."),
("REBELLIOUS / UNCONVENTIONAL","defying orthodoxy",
 "dissident, heresy, heretical, heterodox, iconoclast, insurgent, insurrection, maverick, nonconformist, radical, renegade, revolutionary, subversive",
 "conservative, conventional, hidebound, orthodox, reactionary",
 "heterodox ≈ heretical","iconoclast/maverick = one who breaks with convention; antonyms = orthodox/hidebound."),
("MOCK / DISRESPECT","ridicule or belittle",
 "abase, belittle, condescend, contempt, denigrate, deride, disdain, disparage, jeer, lampoon, patronize, sarcastic, sardonic, satire, scoff, scorn, sneer, snicker, snide, spurn, taunt",None,
 "deride ≈ mock","lampoon/satire = mock in writing; disdain/scorn/spurn = reject contemptuously."),
("PRAISE","express high approval",
 "acclaim, accolade, applaud, approbation, commendable, eulogy, exalt, extol, glorify, hail, laud, lionize, plaudit",None,
 "laud ≈ extol","See §4.1 & §5.1. Direct antonyms = the DISAPPROVE / MOCK groups."),
("AVOID / DODGE","evade",
 "avert, circumvent, deflect, elude, evade, evasive, parry, quibble, shirk, shunt, skirt, swerve",
 "head-on",
 "elude ≈ evade","circumvent = get around (a rule); shirk = dodge a duty."),
("NOT SERIOUS / FRIVOLOUS","light, carefree",
 "blithe, facetious, flippant, frivolous, frivolity, insouciant, levity",
 "grave, gravity",
 "flippant ≈ facetious","levity = lack of seriousness; insouciant = carefree. Antonyms grave/gravity."),
("HORRIFYING / SHOCKING","dreadful",
 "aghast, appalling, egregious, ghastly, grisly, gross, grotesque, gruesome, heinous, hideous, horrendous, monstrous, morbid, unsightly, vile",None,
 "heinous ≈ monstrous","egregious = outrageously bad; grisly/gruesome = causing horror."),
]

lines = []
lines.append("---\n")
lines.append("## 8. Word Groups Rebuilt for Memory\n")
lines.append("> Every thematic **Word Group** from the source, reorganized for active study. For each: the **shared theme**, the full **member list** (faithful to the source), any **antonym sub-group**, the single best **SE pairing** to memorize, and a **hook / distinction**. ⚠ flags the traps. These are your SE/TC raw material — learn each group as one chunk, then drill its antonym group back-to-back.\n")
for name, theme, words, ant, pair, hook in G:
    lines.append(f"### {name}")
    lines.append(f"*{theme}.*  ")
    lines.append(f"**Words:** {words}.  ")
    if ant:
        lines.append(f"**Antonyms:** {ant}.  ")
    lines.append(f"**Best SE pair:** {pair}.  ")
    lines.append(f"**Hook:** {hook}\n")

section = "\n".join(lines) + "\n<!-- SECTION-BREAK -->\n"
path = "GRE-Lexicon-Master-Handbook.md"
doc = open(path, encoding="utf-8").read()
assert doc.count("<!-- SECTION-BREAK -->") == 1
doc = doc.replace("<!-- SECTION-BREAK -->", section, 1)
open(path, "w", encoding="utf-8").write(doc)
print("Inserted Section 8 with", len(G), "groups.")
