# word -> (POS, Root/etymology, Memory hook). Batch 1: A-C.
# Uncertain etymologies marked "(poss.)"; non-Latin origins given by language.
D = {
"abject": ("adj", "ab- (away) + ject (throw)", "thrown down/away → lowest, wretched"),
"abjure": ("v", "ab- (away) + jur (swear)", "swear away → renounce on oath"),
"abnegate": ("v", "ab- (away) + neg (deny)", "deny away from oneself → renounce"),
"abrasive": ("adj", "ab- (away) + ras (scrape)", "scrapes away → harsh, grating"),
"abrogate": ("v", "ab- (away) + rog (ask/propose law)", "propose-away a law → repeal it"),
"absolve": ("v", "ab- (from) + solv (loosen)", "loosen from guilt → set free"),
"abstinence": ("n", "abs- (from) + tin (hold)", "hold back from → self-denial"),
"abut": ("v", "Old Fr. abouter (to border)", "two things 'a-butt' → touch at the edge"),
"accost": ("v", "ad- (to) + cost (rib/side, L. costa)", "come up to your side → approach & speak to"),
"accouterments": ("n", "Fr. accoutrer (to equip)", "a soldier's 'cuttings'/gear → equipment"),
"accrue": ("v", "ad- (to) + cre (grow)", "grows onto → accumulates over time"),
"acme": ("n", "Gk. akmē (highest point)", "the 'ack-me' top → the peak"),
"acolyte": ("n", "Gk. akolouthos (follower)", "a follower/attendant, esp. an assistant"),
"acrid": ("adj", "L. acer/acri (sharp)", "sharp & bitter (cf. acid) → pungent"),
"actuate": ("v", "L. act (do/drive)", "set into act → put in motion"),
"acumen": ("n", "L. acu (sharp/needle)", "sharpness of mind → keen insight"),
"adduce": ("v", "ad- (to) + duc (lead)", "lead forward → bring up as evidence"),
"adroit": ("adj", "Fr. à droit (rightly/to the right)", "'a-droit' = does it right → skillful"),
"adventitious": ("adj", "ad- (to) + ven (come)", "comes to you by chance → accidental"),
"aegis": ("n", "Gk. aigis (Zeus's shield)", "under the shield of → sponsorship/protection"),
"affectation": ("n", "ad- (to) + fect (make)", "a made-up manner → artificial pose"),
"affluence": ("n", "ad- (to) + flu (flow)", "wealth flowing in → abundance"),
"affray": ("n", "Old Fr. esfreer (to frighten)", "a frightful public brawl → noisy fight"),
"affront": ("v", "ad- (to) + front (forehead/face)", "in your face → an open insult"),
"aficionado": ("n", "Sp. aficionar (to inspire affection)", "a devoted fan/enthusiast"),
"agnostic": ("n", "a- (without) + gnos (knowledge)", "without knowledge of God's existence"),
"alibi": ("n", "L. alibi (elsewhere)", "claim you were 'else-bi'/elsewhere → defense"),
"allege": ("v", "L. allegare (to send/cite)", "assert without proof → claim"),
"allude": ("v", "ad- (to) + lud (play)", "play toward → refer indirectly"),
"ally": ("v", "ad- (to) + lig (bind)", "bound to → a partner/associate"),
"altercation": ("n", "L. alter (other)", "a heated back-and-forth with another → quarrel"),
"alternate": ("v", "L. alter (other/one of two)", "switch to the other → take turns"),
"amenable": ("adj", "Fr. amener (to lead to)", "can be led → willing, agreeable"),
"amicable": ("adj", "L. amicus (friend)", "friend-like → peaceable (of arrangements)"),
"amorphous": ("adj", "a- (without) + morph (form)", "without form → shapeless"),
"amplitude": ("n", "L. amplus (large)", "ample-ness → breadth, abundance"),
"anchorite": ("n", "Gk. anachorein (to withdraw)", "one who withdraws → a hermit"),
"angst": ("n", "Ger. Angst (fear/anxiety)", "deep dread about the world → anxiety"),
"antagonistic": ("adj", "anti- (against) + agon (struggle/contest)", "struggling against → hostile"),
"antithesis": ("n", "anti- (against) + thesis (placing)", "set against → the direct opposite"),
"aphorism": ("n", "Gk. aphorizein (to define/mark off)", "a pithy defined truth → maxim"),
"apocalyptic": ("adj", "Gk. apokalyptein (to uncover/reveal)", "of a revelation → prophetic, end-of-world"),
"apostasy": ("n", "apo- (away) + sta (stand)", "stand away from → desertion of faith"),
"apposite": ("adj", "ad- (to) + posit (placed)", "well-placed → strikingly apt"),
"arable": ("adj", "L. arare (to plow)", "able to be plowed → farmable land"),
"arbitrary": ("adj", "L. arbiter (judge)", "by a judge's mere whim → based on opinion alone"),
"arcane": ("adj", "L. arcanus (secret/chest)", "locked in a chest → secret, mysterious"),
"archaic": ("adj", "Gk. archaios (ancient)", "from the start/old → outdated"),
"archetype": ("n", "Gk. arche (first) + typ (model)", "the first model → the original pattern"),
"ardor": ("n", "L. ardere (to burn)", "burning feeling → passion, zeal"),
"arraign": ("v", "Old Fr. araisnier (to call to account)", "call into court → charge formally"),
"arrant": ("adj", "var. of 'errant' (wandering)", "downright/utter (a notorious one)"),
"array": ("n", "Old Fr. areer (to arrange)", "an arranged display → impressive collection"),
"arrogate": ("v", "ad- (to) + rog (ask/claim)", "claim to oneself unjustly → seize"),
"artifice": ("n", "L. arti (skill) + fic (make)", "skillful making → a cunning trick"),
"askance": ("adv", "origin uncertain (poss.)", "look 'a-skance'/sideways → with distrust"),
"assay": ("v", "Old Fr. assai (a trial/test)", "to test/try (esp. metal purity)"),
"astute": ("adj", "L. astus (craft/cunning)", "shrewdly clever → keen-minded"),
"attrition": ("n", "ad- (to) + trit (rub)", "a rubbing/wearing down → gradual weakening"),
"augment": ("v", "L. augere (to increase)", "make bigger → increase"),
"augur": ("v", "L. augur (Roman seer)", "read omens → foretell, be a sign of"),
"august": ("adj", "L. augustus (venerable)", "majestic & awe-inspiring (cf. Emperor Augustus)"),
"autarchy": ("n", "auto- (self) + arch (rule)", "self-rule → absolute sovereignty"),
"avant-garde": ("n", "Fr. 'advance guard'", "the front line of the new → experimental art"),
"avarice": ("n", "L. avere (to crave)", "'have-a-rich' craving → greed for wealth"),
"avid": ("adj", "L. avere (to crave)", "craving → eager, enthusiastic"),
"avocation": ("n", "ab- (away) + voc (calling)", "a calling away from work → a hobby"),
"awry": ("adj", "a- + wry (twisted)", "twisted to one side → wrong, off course"),
"axiom": ("n", "Gk. axioma (worthy/accepted)", "an accepted truth → self-evident principle"),
"bacchanal": ("n", "L. Bacchus (god of wine)", "a Bacchus-feast → drunken revelry"),
"badger": ("v", "from 'badger' the animal (baited)", "to bait like a badger → nag, harass"),
"baffle": ("v", "origin uncertain (poss.)", "to confound → perplex"),
"bailiwick": ("n", "bailiff + wick (Old Eng. district)", "a bailiff's district → one's area of expertise"),
"balderdash": ("n", "origin uncertain (poss.)", "frothy nonsense → senseless talk"),
"baleful": ("adj", "Old Eng. bealu (evil/harm)", "full of bale/harm → menacing, sinister"),
"balk": ("v", "Old Eng. balca (ridge/obstacle)", "hit a ridge → stop short, refuse"),
"baloney": ("n", "from Bologna sausage", "cheap sausage → nonsense"),
"bamboozle": ("v", "origin uncertain (poss.)", "to bamboozle → trick, deceive, confuse"),
"bane": ("n", "Old Eng. bana (slayer/poison)", "a poison → cause of ruin (cf. baneful)"),
"banter": ("n", "origin uncertain (poss.)", "playful teasing → light ridicule"),
"barb": ("n", "L. barba (beard/hook)", "a sharp hook → a stinging remark"),
"baroque": ("adj", "Port. barroco (irregular pearl)", "ornate, irregular 17th-c. style"),
"bastion": ("n", "It. bastire (to build)", "a built fortification → a stronghold"),
"bathos": ("n", "Gk. bathos (depth)", "a plunge from lofty to trivial → anticlimax"),
"bawdy": ("adj", "from 'bawd' (madam)", "brothel-talk → obscene, indecent"),
"beatific": ("adj", "L. beatus (blessed) + fic (make)", "showing bliss → blessedly serene"),
"becoming": ("adj", "be- + come (suit)", "suits you → attractive, appropriate"),
"bedlam": ("n", "Bethlehem (London madhouse)", "the old asylum → chaos, uproar"),
"beguile": ("v", "be- (thoroughly) + guile (trickery)", "lead by guile → charm/deceive"),
"behemoth": ("n", "Heb. behemoth (huge beast)", "a giant creature → anything enormous"),
"behoove": ("v", "Old Eng. behofian (to need)", "it 'be-hooves' → is fitting/necessary"),
"beleaguer": ("v", "Du. belegeren (to besiege)", "to besiege → harass, beset"),
"bellicose": ("adj", "L. bellum (war)", "war-like → eager to fight"),
"bemused": ("adj", "be- + muse", "lost in thought → confused, bewildered"),
"benchmark": ("n", "surveyor's mark on a bench", "a fixed reference mark → a standard"),
"benediction": ("n", "bene- (good) + dict (say)", "good words said → a blessing"),
"beneficence": ("n", "bene- (good) + fic (do)", "doing good → kindness, charity"),
"beneficial": ("adj", "bene- (good) + fic (do)", "does good → helpful, advantageous"),
"benign": ("adj", "bene- (good) + gen (born/kind)", "good-natured → mild, harmless"),
"bequeath": ("v", "Old Eng. becwethan (to say/will)", "to 'be-say' in a will → leave as legacy"),
"berate": ("v", "be- (thoroughly) + rate (scold)", "scold thoroughly → chew out"),
"bereavement": ("n", "be- + reave (rob/deprive)", "robbed of a loved one → grief"),
"berserk": ("adj", "Norse berserkr (frenzied warrior)", "like a berserker → wildly violent"),
"bete noire": ("n", "Fr. 'black beast'", "your 'black beast' → a dreaded bane/pet peeve"),
"bigotry": ("n", "Fr. bigot (hypocrite)", "intolerant prejudice"),
"bilious": ("adj", "L. bilis (bile)", "full of bile → ill-tempered, peevish"),
"bizarre": ("adj", "It. bizzarro (angry/odd)", "strikingly odd → weird"),
"blanch": ("v", "Fr. blanc (white)", "turn white → go pale"),
"blase": ("adj", "Fr. blasé (cloyed)", "over-satisfied → bored, unimpressed"),
"blatant": ("adj", "coined by Spenser (poss. L. blatire, babble)", "loudly obvious → glaringly conspicuous"),
"bleak": ("adj", "Old Norse bleikr (pale)", "pale & barren → cheerless, gloomy"),
"blithe": ("adj", "Old Eng. blithe (joyous)", "carefree → merry, lighthearted"),
"bohemian": ("n", "Fr. (gypsy of Bohemia)", "an unconventional, free-living artist"),
"bon mot": ("n", "Fr. 'good word'", "a clever, witty remark"),
"bondage": ("n", "Old Eng. bonda (bound)", "being bound → slavery"),
"bowdlerize": ("v", "after Thomas Bowdler (expurgator)", "to 'Bowdler-ize' → prudishly censor"),
"braggadocio": ("n", "Spenser's boastful character", "empty boasting"),
"bravado": ("n", "Sp. bravata (boast)", "a swaggering pretense of bravery"),
"bravura": ("n", "It. bravura (skill/spirit)", "a dazzling display of daring/skill"),
"brawl": ("n", "origin uncertain (poss.)", "a noisy fight"),
"breakthrough": ("n", "break + through", "a barrier broken → a major advance"),
"broach": ("v", "L. brocca (spike) → tap a cask", "to pierce/open → bring up a topic"),
"brook": ("v", "Old Eng. brucan (to use/endure)", "to put up with → tolerate"),
"bucolic": ("adj", "Gk. boukolos (cowherd)", "of cowherds → rustic, pastoral"),
"bug": ("v", "from 'bug' (insect)", "to pester like a bug → annoy"),
"bumptious": ("adj", "bump + (pretentious)", "obtrusively bumping in → conceited"),
"bungle": ("v", "origin uncertain (poss.)", "to botch clumsily → blunder"),
"buoyancy": ("n", "Sp. boyar (to float)", "the float-iness → cheerfulness, lift"),
"burnish": ("v", "Fr. brunir (to make brown/shine)", "rub till it shines → polish"),
"bustle": ("n", "origin uncertain (poss.)", "noisy busy activity → flurry"),
"cabal": ("n", "Heb. qabbalah (secret doctrine)", "a secret plotting group → clique"),
"cache": ("n", "Fr. cacher (to hide)", "a hidden store"),
"cadence": ("n", "L. cad (fall)", "the falling rhythm of the voice → measured flow"),
"cahoots": ("n", "origin uncertain (poss. Fr. cahute, cabin)", "secretly partnered → in collusion"),
"caitiff": ("n", "L. captivus (captive/wretch)", "a captive wretch → cowardly villain"),
"cajole": ("v", "Fr. cajoler (to coax)", "sweet-talk → coax with flattery"),
"callow": ("adj", "Old Eng. calu (bald/unfledged)", "unfeathered chick → immature, inexperienced"),
"caper": ("n", "L. caper (goat)", "a goat-like leap → a prank or escapade"),
"capitulate": ("v", "L. capitulum (heading/terms)", "agree to terms → surrender"),
"carte blanche": ("n", "Fr. 'blank card'", "a blank check → unrestricted authority"),
"categorical": ("adj", "Gk. kategoria (assertion)", "asserted absolutely → unqualified, definite"),
"catharsis": ("n", "Gk. katharsis (cleansing)", "an emotional cleansing → purging of feeling"),
"catholic": ("adj", "Gk. kata-holos (whole/universal)", "universal → broad-minded, wide-ranging"),
"cavil": ("v", "L. cavilla (jeering)", "raise petty objections → quibble"),
"chagrin": ("n", "Fr. chagrin (grief/rough skin)", "vexation from failure → embarrassment"),
"cheeseparing": ("adj", "paring the cheese rind thin", "scraping every bit → stingy"),
"chide": ("v", "Old Eng. cidan (to scold)", "to scold mildly"),
"chimera": ("n", "Gk. Chimaira (monster of mixed parts)", "an impossible fancy → wild illusion"),
"choleric": ("adj", "Gk. chole (bile, the angry humor)", "full of choler → quick to anger"),
"churlish": ("adj", "Old Eng. ceorl (peasant)", "peasant-like → rude, ill-tempered"),
"chutzpah": ("n", "Yiddish (gall/nerve)", "shameless boldness → audacity"),
"circumlocution": ("n", "circum- (around) + loqu (speak)", "talking around → roundabout speech"),
"clairvoyant": ("adj", "Fr. clair (clear) + voir (see)", "clear-seeing → able to perceive the hidden"),
"coalesce": ("v", "co- (together) + alesc (grow)", "grow together → merge into one"),
"cogitate": ("v", "L. cogitare (to think)", "to think hard → ponder, reflect"),
"cognizant": ("adj", "L. cognoscere (to know)", "knowing → aware"),
"cohere": ("v", "co- (together) + her (stick)", "stick together → be consistent"),
"coincident": ("adj", "co- (together) + incid (fall upon)", "falling together → occurring at once"),
"collate": ("v", "com- (together) + lat (bring)", "bring together → compare/assemble in order"),
"colossal": ("adj", "Gk. kolossos (giant statue)", "Colossus-sized → huge"),
"comely": ("adj", "Old Eng. cymlic (lovely)", "pleasing in looks → handsome, graceful"),
"commiserate": ("v", "com- (with) + miser (wretched)", "share the misery → feel pity"),
"complacent": ("adj", "com- + plac (please)", "pleased with oneself → smug"),
"concomitant": ("adj", "com- (with) + comit (companion)", "accompanying → going along with"),
"concord": ("n", "com- (together) + cord (heart)", "hearts together → agreement, harmony"),
"condescend": ("v", "com- + de- (down) + scend (climb)", "stoop down → talk down patronizingly"),
"confabulate": ("v", "com- (together) + fabul (talk)", "talk together → chat informally"),
"confute": ("v", "com- + fut (beat/pour)", "beat down an argument → prove wrong"),
"congeal": ("v", "com- (together) + gel (freeze)", "freeze together → solidify"),
"congenial": ("adj", "com- (together) + genial (of one's nature)", "of the same nature → agreeable"),
"conjecture": ("n", "com- + ject (throw)", "throw ideas together → a guess"),
"consecrate": ("v", "com- + sacr (sacred)", "make wholly sacred → dedicate, hallow"),
"consort": ("n", "com- (with) + sort (lot/fate)", "one sharing your lot → a spouse/companion"),
"construe": ("v", "com- + stru (build)", "build a meaning → interpret"),
"contingent": ("adj", "com- + ting (touch/happen)", "depends on what happens → conditional"),
"contumacy": ("n", "L. contumax (defiant/swollen)", "swollen defiance → stubborn disobedience"),
"contumely": ("n", "L. contumelia (insult)", "insolent abuse → scornful insult"),
"convalescence": ("n", "com- + valesc (grow strong)", "growing strong again → recovery"),
"convivial": ("adj", "com- (together) + viv (live)", "living/feasting together → festive, sociable"),
"copious": ("adj", "L. copia (plenty)", "in plenty → abundant"),
"cornucopia": ("n", "L. cornu (horn) + copia (plenty)", "horn of plenty → abundance"),
"corporal": ("adj", "L. corpus (body)", "of the body → bodily"),
"covenant": ("n", "com- (together) + ven (come)", "a coming-together agreement → binding pact"),
"crass": ("adj", "L. crassus (thick/dense)", "thick-headed → grossly coarse, stupid"),
"credible": ("adj", "L. cred (believe)", "believable → worthy of belief"),
"credo": ("n", "L. credo (I believe)", "an 'I believe' statement → a creed"),
"crotchet": ("n", "Fr. crochet (hook)", "a quirky 'hook' in the mind → odd whim"),
"cynosure": ("n", "Gk. kynosoura (dog's tail/Pole Star)", "the guiding star → center of attention"),
}
