# Batch 2: D-O.
D = {
"dawdle": ("v", "origin uncertain (poss.)", "to dilly-dawdle → waste time, linger"),
"debauch": ("v", "Fr. débaucher (to lead astray)", "lead into excess → corrupt morally"),
"debrief": ("v", "de- (reverse) + brief", "un-brief → question after a mission"),
"decadence": ("n", "de- (down) + cad (fall)", "a falling-down → moral decline"),
"defamation": ("n", "de- (away) + fam (reputation)", "stripping reputation → slander/libel"),
"delineation": ("n", "de- + line (line)", "drawing the lines → a portrayal"),
"demagogue": ("n", "Gk. demos (people) + agogos (leader)", "a people-leader who stirs passions"),
"denotation": ("n", "de- + not (mark)", "the marked-out literal meaning"),
"denouement": ("n", "Fr. dénouer (to untie)", "the untying → final outcome of a plot"),
"depravity": ("n", "de- (down) + prav (crooked)", "bent down → moral corruption"),
"derelict": ("adj", "de- + relinqu (forsake)", "forsaken → neglectful; abandoned"),
"desecrate": ("v", "de- (reverse) + sacr (sacred)", "un-sacred → violate the holy"),
"despicable": ("adj", "de- (down) + spic (look)", "looked down on → contemptible"),
"devious": ("adj", "de- (off) + via (road)", "off the road → winding; underhanded"),
"diaphanous": ("adj", "dia- (through) + phan (show)", "light shows through → sheer, gauzy"),
"disheveled": ("adj", "Fr. des- + chevel (hair)", "hair undone → untidy, unkempt"),
"dissipate": ("v", "dis- (apart) + sip (throw)", "scatter apart → disperse; squander"),
"dolorous": ("adj", "L. dolor (pain/grief)", "full of dolor → mournful, sad"),
"double entendre": ("n", "Fr. 'double meaning'", "a phrase with two senses (one risqué)"),
"dregs": ("n", "Old Norse dregg (sediment)", "the sediment → the worst/lowest part"),
"duress": ("n", "L. durus (hard)", "hard pressure → coercion by force"),
"efface": ("v", "ex- (out) + face", "rub out the face of → erase"),
"effete": ("adj", "L. effetus (worn out by bearing)", "spent → having lost vitality"),
"effulgent": ("adj", "ex- (out) + fulg (shine)", "shining out → radiant, brilliant"),
"effusive": ("adj", "ex- (out) + fus (pour)", "pouring out → gushing with emotion"),
"egoism": ("n", "L. ego (I)", "all about 'I' → selfishness, self-interest"),
"elan": ("n", "Fr. élan (dash/rush)", "spirited dash → verve, enthusiasm"),
"emaciated": ("adj", "ex- + maci (leanness)", "made lean → very thin, wasted"),
"emasculate": ("v", "ex- (out) + mascul (male)", "remove the virility → weaken"),
"embezzle": ("v", "Old Fr. besillier (to ravage)", "filch entrusted funds → steal"),
"encomium": ("n", "Gk. enkomion (eulogy)", "high formal praise → a tribute"),
"ennui": ("n", "Fr. ennui (boredom; cf. annoy)", "weary discontent → boredom"),
"epicure": ("n", "after Epicurus (pleasure)", "a refined pleasure-seeker → gourmet"),
"errant": ("adj", "L. errare (to wander/err)", "wandering; straying from right"),
"ersatz": ("adj", "Ger. Ersatz (replacement)", "a substitute → inferior imitation"),
"eschew": ("v", "Old Fr. eschiver (to shun)", "to shun, avoid deliberately"),
"euphonious": ("adj", "eu- (good) + phon (sound)", "good sound → sweet-sounding"),
"evince": ("v", "ex- (out) + vinc (conquer/show)", "draw out → show clearly"),
"exasperate": ("v", "ex- + asper (rough)", "make rough → irritate intensely"),
"excoriate": ("v", "ex- (off) + cori (skin/hide)", "strip the skin off → denounce harshly"),
"excruciating": ("adj", "ex- + cruci (cross)", "as if on a cross → agonizing"),
"exotic": ("adj", "Gk. exo (outside)", "from outside → foreign, strikingly unusual"),
"expedite": ("v", "ex- + ped (foot)", "free the feet → speed up"),
"expunge": ("v", "ex- (out) + pung (prick)", "prick out → delete, erase"),
"extricate": ("v", "ex- (out) + tric (entanglements)", "out of the tangle → free"),
"exude": ("v", "ex- (out) + sud (sweat)", "sweat out → ooze, give off"),
"exult": ("v", "ex- + sult (leap)", "leap up for joy → rejoice greatly"),
"facile": ("adj", "L. fac (do/make)", "easily done → easy; superficial"),
"factitious": ("adj", "L. fact (made)", "manufactured → artificial, not genuine"),
"fallible": ("adj", "L. fall (deceive/fail)", "able to fail → liable to err"),
"faux pas": ("n", "Fr. 'false step'", "a social blunder"),
"fetid": ("adj", "L. fetere (to stink)", "stinking → foul-smelling"),
"fetter": ("n", "Old Eng. fetor (foot-chain)", "a foot-chain → a restraint"),
"fiasco": ("n", "It. fiasco (bottle; 'make a bottle')", "a complete humiliating failure"),
"fidelity": ("n", "L. fid (faith)", "faithfulness; accuracy"),
"finesse": ("n", "Fr. fin (fine)", "fine skill → refined tact/technique"),
"finite": ("adj", "L. finis (end/limit)", "having an end → limited"),
"flaccid": ("adj", "L. flaccus (flabby)", "flabby → limp, soft"),
"flagrant": ("adj", "L. flagrare (to blaze)", "blazing → glaringly bad"),
"flamboyant": ("adj", "Fr. flamboyer (to flame)", "flame-like → showy, extravagant"),
"forfeit": ("v", "Fr. forfait (crime/penalty)", "lose as a penalty → give up"),
"foster": ("v", "Old Eng. fostrian (to nourish)", "to nourish → bring up; promote"),
"frailty": ("n", "L. frangere (to break)", "breakable-ness → weakness"),
"fritter": ("v", "from 'fitters' (fragments)", "break into bits → waste piecemeal"),
"furtive": ("adj", "L. fur (thief)", "thief-like → stealthy, secret"),
"gauche": ("adj", "Fr. gauche (left/clumsy)", "'left-handed' → socially awkward"),
"generic": ("adj", "L. genus (kind/class)", "of a whole class → general, non-specific"),
"genial": ("adj", "L. genialis (festive/of birth)", "warm-natured → cheerful, friendly"),
"genteel": ("adj", "Fr. gentil (well-born)", "of polite society → refined, elegant"),
"germane": ("adj", "L. germanus (of the same stock)", "akin to the topic → relevant"),
"glean": ("v", "Old Fr. glener (to gather grain)", "gather leftovers bit by bit → collect"),
"glut": ("v", "L. gluttire (to swallow)", "gulp down → oversupply, stuff full"),
"gratuitous": ("adj", "L. gratis (free)", "given free/unprovoked → uncalled-for"),
"haggard": ("adj", "Fr. (a wild hawk)", "wild-eyed & gaunt → worn-looking"),
"hallowed": ("adj", "Old Eng. halig (holy)", "made holy → consecrated, revered"),
"hapless": ("adj", "hap (luck) + -less", "luck-less → unfortunate"),
"hedonism": ("n", "Gk. hedone (pleasure)", "pleasure as the goal → pursuit of pleasure"),
"hoi polloi": ("n", "Gk. 'the many'", "the masses → the common people"),
"homogeneous": ("adj", "homo- (same) + gen (kind)", "of the same kind → uniform"),
"humane": ("adj", "L. humanus (human)", "showing the best of human feeling → kind"),
"humdrum": ("adj", "reduplication of 'hum'", "a monotonous hum → dull, tedious"),
"ignoramus": ("n", "L. 'we do not know'", "one who knows nothing → a dolt"),
"imbue": ("v", "L. imbuere (to soak/stain)", "soak through → permeate with feeling"),
"immanent": ("adj", "in- (in) + man (remain)", "remaining within → inherent"),
"imminent": ("adj", "in- + min (project/overhang)", "overhanging → about to happen"),
"impassioned": ("adj", "in- (in) + passion", "filled with passion → fervent"),
"impeccable": ("adj", "in- (not) + pecc (sin/fault)", "without sin → flawless"),
"imperious": ("adj", "L. imperium (command)", "commanding → arrogantly domineering"),
"impetuous": ("adj", "in- + pet (rush/seek)", "rushing in → rash, impulsive"),
"impromptu": ("adj", "L. in promptu (in readiness)", "off the cuff → unrehearsed"),
"inane": ("adj", "L. inanis (empty)", "empty → silly, pointless"),
"inclement": ("adj", "in- (not) + clement (mild)", "not mild → stormy, harsh"),
"incredulous": ("adj", "in- (not) + cred (believe)", "unbelieving → skeptical"),
"inculpate": ("v", "in- (in) + culp (blame/fault)", "put the blame on → incriminate"),
"indigenous": ("adj", "indi- (within) + gen (born)", "born within a place → native"),
"inept": ("adj", "in- (not) + apt (fit)", "not apt → clumsy, unsuitable"),
"intrepid": ("adj", "in- (not) + trepid (alarmed)", "without trembling → fearless"),
"jaded": ("adj", "from 'jade' (worn-out horse)", "worn out → dulled, wearied"),
"jubilation": ("n", "L. jubilare (to shout for joy)", "great rejoicing → exultation"),
"juggernaut": ("n", "Hindi Jagannath (a temple idol's cart)", "an unstoppable crushing force"),
"kaleidoscopic": ("adj", "Gk. kalos (beautiful) + eidos (form) + skop (look)", "ever-shifting like a kaleidoscope"),
"labyrinthine": ("adj", "Gk. labyrinthos (maze)", "maze-like → intricate, perplexing"),
"lackadaisical": ("adj", "from 'lackaday' (alas)", "listless, half-hearted"),
"laissez faire": ("n", "Fr. 'let do/leave alone'", "hands-off policy → non-interference"),
"languid": ("adj", "L. languere (to be weak)", "drooping → listless, lacking energy"),
"lascivious": ("adj", "L. lascivus (lustful)", "wanton → lewd, lustful"),
"leit motif": ("n", "Ger. Leitmotiv (leading motif)", "a recurring theme"),
"lewd": ("adj", "Old Eng. læwede (lay/common)", "vulgar → obscene, crude"),
"limbo": ("n", "L. limbus (edge/border)", "the edge/border state → uncertain waiting"),
"limpid": ("adj", "L. limpidus (clear)", "crystal clear → transparent, lucid"),
"loath": ("adj", "Old Eng. lath (hostile)", "averse → very reluctant, unwilling"),
"loathe": ("v", "Old Eng. lathian (to hate)", "to detest → feel disgust for"),
"luminous": ("adj", "L. lumen (light)", "full of light → glowing, brilliant"),
"lurid": ("adj", "L. luridus (pale/ghastly)", "ghastly glow → sensational, shocking"),
"luxurious": ("adj", "L. luxus (excess)", "of rich excess → sumptuous, comfortable"),
"macabre": ("adj", "Fr. (Dance of Death)", "of death & decay → gruesome, grim"),
"magnate": ("n", "L. magnus (great)", "a great one → an industry tycoon"),
"magnum opus": ("n", "L. 'great work'", "an artist's masterpiece"),
"maladroit": ("adj", "mal- (badly) + à droit (rightly)", "not done rightly → clumsy"),
"malediction": ("n", "mal- (bad) + dict (say)", "bad words said → a curse"),
"marauder": ("n", "Fr. maraud (rogue)", "a raider who plunders"),
"marginalize": ("v", "L. margo (edge)", "push to the margin → exclude, sideline"),
"mellifluous": ("adj", "L. mel (honey) + flu (flow)", "flowing like honey → sweet-sounding"),
"mellow": ("adj", "Old Eng. mearu (soft)", "ripe & soft → mild, mature"),
"mendicant": ("n", "L. mendicare (to beg)", "a beggar"),
"misconstrue": ("v", "mis- (wrongly) + construe", "build the wrong meaning → misinterpret"),
"mordacious": ("adj", "L. mord (bite)", "biting → caustic, capable of wounding"),
"moribund": ("adj", "L. mori (to die)", "near death → dying, lacking vitality"),
"mortify": ("v", "L. mort (death) + fic (make)", "to 'deaden' with shame → humiliate"),
"naive": ("adj", "Fr. naïf (natural/native)", "unspoiled → artless, unworldly"),
"nefarious": ("adj", "L. nefas (wrong/unspeakable)", "against divine law → extremely wicked"),
"nimble": ("adj", "Old Eng. næmel (quick to grasp)", "quick → agile in body or mind"),
"noxious": ("adj", "L. nox/noc (harm)", "harmful → poisonous, unwholesome"),
"objurgate": ("v", "ob- (against) + jurg (chide)", "chide against → scold sharply"),
"obliterate": ("v", "ob- + liter (letter)", "blot out the letters → wipe out"),
"obsolete": ("adj", "L. obsolescere (to wear out)", "worn out of use → outdated"),
"obtrude": ("v", "ob- (against) + trud (thrust)", "thrust forward unwanted → intrude"),
"obtuse": ("adj", "ob- + tus (beaten/blunt)", "blunted → dull-witted, slow"),
"occlude": ("v", "ob- (against) + clud (close)", "close up → block, obstruct"),
"ominous": ("adj", "L. omen (omen)", "omen-bearing → threatening"),
"opportune": ("adj", "L. ob portum (toward port)", "wind to harbor → timely, favorable"),
"orotund": ("adj", "L. ore rotundo (round mouth)", "round-mouthed → resonant; pompous"),
"override": ("v", "over + ride", "ride over → overrule, prevail over"),
}
