# Batch 3: P-Z.
D = {
"paean": ("n", "Gk. paian (hymn to Apollo)", "a hymn of praise"),
"palpable": ("adj", "L. palpare (to touch)", "touchable → readily perceived, obvious"),
"pandemonium": ("n", "pan- (all) + daimon (demon); Milton's hell", "all-demons place → wild uproar"),
"paradigm": ("n", "para- (beside) + deig (show)", "a shown example → a model, pattern"),
"parity": ("n", "L. par (equal)", "equalness → equivalence in rank/value"),
"parochial": ("adj", "L. parochia (parish)", "of one parish → narrow, provincial"),
"pedestrian": ("adj", "L. ped (foot)", "on foot → plodding, dull, commonplace"),
"peevish": ("adj", "origin uncertain (poss.)", "fretful → irritable, querulous"),
"penitent": ("adj", "L. paenitere (to repent)", "repenting → feeling guilt, contrite"),
"penury": ("n", "L. penuria (want)", "an empty purse → extreme poverty"),
"pernicious": ("adj", "per- (thoroughly) + nec (kill)", "deadly → very harmful"),
"perspicuous": ("adj", "per- (through) + spic (see)", "see-through → clearly expressed, lucid"),
"perturb": ("v", "per- (thoroughly) + turb (disturb)", "stir up → disquiet greatly"),
"pinnacle": ("n", "L. pinna (peak/wing)", "the topmost peak → highest point"),
"pithy": ("adj", "Old Eng. pitha (pith/core)", "full of pith → terse and meaty"),
"portend": ("v", "por- (forth) + tend (stretch)", "stretch forth a sign → foretell, presage"),
"potentate": ("n", "L. potens (powerful)", "a powerful one → a ruler"),
"preclude": ("v", "prae- (before) + clud (shut)", "shut out beforehand → prevent"),
"precocious": ("adj", "prae- (before) + coqu (ripen)", "ripe early → advanced for one's age"),
"presage": ("v", "prae- (before) + sag (perceive)", "perceive beforehand → foreshadow"),
"procrastinate": ("v", "pro- (forward) + cras (tomorrow)", "push to tomorrow → delay"),
"prolix": ("adj", "pro- (forth) + lix (poured)", "poured out at length → tediously wordy"),
"prosaic": ("adj", "L. prosa (prose)", "prose-like → unimaginative, dull"),
"proselytize": ("v", "Gk. proselytos (newcomer/convert)", "to win converts"),
"protract": ("v", "pro- (forward) + tract (draw)", "draw out → prolong"),
"proviso": ("n", "L. proviso (it being provided)", "a stipulated condition → a clause"),
"puerile": ("adj", "L. puer (boy)", "boyish → childishly silly"),
"pugnacious": ("adj", "L. pugn (fight/fist)", "fond of fighting → combative"),
"puissant": ("adj", "Fr. (powerful)", "having great power → mighty"),
"punctilious": ("adj", "L. punctum (point)", "minding every point → exact about details"),
"qualm": ("n", "Old Eng. cwealm (sickness)", "a pang → uneasy doubt of conscience"),
"quandary": ("n", "origin uncertain (poss.)", "a perplexing fix → a dilemma"),
"quintessence": ("n", "L. quinta essentia (fifth essence)", "the purest essence → perfect example"),
"quizzical": ("adj", "from 'quiz' (poss.)", "questioning → puzzled, mildly mocking"),
"racy": ("adj", "from 'race' (lively flavor)", "lively & vigorous; risqué"),
"raison d' etre": ("n", "Fr. 'reason for being'", "the justification for existing"),
"rambunctious": ("adj", "origin uncertain (poss.)", "wild and boisterous, unruly"),
"rancor": ("n", "L. rancere (to be rancid)", "rancid bitterness → deep spiteful hatred"),
"rapacious": ("adj", "L. rap (seize)", "grasping → greedy, plundering"),
"raucous": ("adj", "L. raucus (hoarse)", "hoarse & rough → harsh, disorderly"),
"ravenous": ("adj", "L. rap (seize) via Fr. ravine", "seizing with hunger → voracious"),
"raw": ("adj", "Old Eng. hreaw (uncooked)", "uncooked/unprocessed → inexperienced"),
"raze": ("v", "L. radere (to scrape)", "scrape to the ground → demolish"),
"recapitulate": ("v", "re- (again) + capit (head/heading)", "re-head the points → summarize"),
"recrimination": ("n", "re- (back) + crimin (accuse)", "accuse back → counter-accusation"),
"rectitude": ("n", "L. rectus (straight/right)", "straightness → moral uprightness"),
"redoubtable": ("adj", "Fr. redouter (to dread)", "to be dreaded → formidable"),
"remonstrate": ("v", "re- + monstr (show/warn)", "show in protest → plead against"),
"renege": ("v", "re- + neg (deny)", "deny again → go back on a promise"),
"rescind": ("v", "re- (back) + scind (cut)", "cut back → repeal, make void"),
"resilient": ("adj", "re- (back) + sil (leap)", "leaps back → springs back, recovers"),
"robust": ("adj", "L. robur (oak/strength)", "oak-strong → sturdy, vigorous"),
"rudiment": ("n", "L. rudis (unwrought/raw)", "a raw beginning → a first principle"),
"sagacity": ("n", "L. sagax (keen-scented)", "keen perception → shrewd wisdom"),
"salacious": ("adj", "L. salax (lustful)", "leaping with lust → lewd, obscene"),
"salutary": ("adj", "L. salus (health)", "health-giving → beneficial"),
"sap": ("v", "Fr. saper (to undermine)", "drain the sap → weaken gradually"),
"sardonic": ("adj", "Gk. sardonios (bitter laugh)", "bitterly mocking → sneering, derisive"),
"sartorial": ("adj", "L. sartor (tailor)", "of the tailor → relating to clothing"),
"saturnine": ("adj", "L. Saturnus (planet of gloom)", "born under Saturn → gloomy, morose"),
"savant": ("n", "Fr. (knowing one)", "a learned person → a scholar, sage"),
"scintillate": ("v", "L. scintilla (spark)", "throw sparks → sparkle, twinkle"),
"scruple": ("n", "L. scrupulus (sharp pebble)", "a pebble in the conscience → a moral qualm"),
"scrupulous": ("adj", "L. scrupulus (sharp pebble)", "minding every qualm → conscientious, exact"),
"scurrilous": ("adj", "L. scurra (buffoon)", "buffoon-like abuse → grossly insulting"),
"scurry": ("v", "from 'hurry-scurry'", "to scamper → move hurriedly"),
"seamy": ("adj", "the 'seamy' (rough) side of cloth", "the underside → sordid, degraded"),
"sear": ("v", "Old Eng. sear (dry/withered)", "scorch dry → burn the surface"),
"sedate": ("adj", "L. sedare (to settle/calm)", "settled → calm, composed, serious"),
"sedulous": ("adj", "L. sedulo (diligently)", "persistently careful → diligent"),
"sentient": ("adj", "L. sentire (to feel)", "feeling → able to perceive"),
"sermon": ("n", "L. sermo (discourse)", "a religious discourse → a moralizing talk"),
"servile": ("adj", "L. servus (slave)", "slave-like → submissive, fawning"),
"shelve": ("v", "from 'shelf'", "set on a shelf → put aside, defer"),
"shirk": ("v", "poss. Ger. Schurke (rogue)", "dodge a duty → evade work"),
"simper": ("v", "origin uncertain (poss.)", "to smirk → smile affectedly"),
"skinflint": ("n", "one who'd 'skin a flint' for gain", "a miser → a stingy person"),
"skirmish": ("n", "Old Fr. escarmouche", "a minor brief clash → small fight"),
"slack": ("n", "Old Eng. slæc (loose/lazy)", "looseness → a decline, lazy ease"),
"slake": ("v", "Old Eng. slacian (to slacken)", "slacken a thirst → satisfy, quench"),
"slew": ("n", "Irish slua (multitude)", "a great number → a lot"),
"slippage": ("n", "from 'slip'", "a slipping → decline from a standard"),
"sodden": ("adj", "old past part. of 'seethe'", "soaked through → thoroughly wet"),
"solicitous": ("adj", "L. sollicitus (anxious)", "stirred-up with care → anxiously attentive"),
"sombre": ("adj", "Fr. sombre (shadowy)", "under shadow → gloomy, melancholy"),
"spasmodic": ("adj", "Gk. spasma (spasm)", "in spasms → fitful, intermittent"),
"squander": ("v", "origin uncertain (poss.)", "scatter wastefully → waste money"),
"squelch": ("v", "imitative (squishing sound)", "stamp out → suppress, crush"),
"statute": ("n", "L. statuere (to set up)", "a set-up law → a written enactment"),
"stealth": ("n", "Old Eng. stelan (to steal)", "thief-like quiet → secret movement"),
"steep": ("adj", "Old Eng. steap (high)", "sharply high → excessive, extreme"),
"stentorian": ("adj", "Gk. Stentor (loud-voiced herald)", "Stentor-loud → extremely loud"),
"stickler": ("n", "Old Eng. stihtan (to set in order)", "one who insists on details"),
"stratagem": ("n", "Gk. strategos (general)", "a general's trick → a cunning ruse"),
"stultify": ("v", "L. stultus (foolish)", "make foolish → frustrate, render useless"),
"stupefy": ("v", "L. stupere (to be stunned)", "stun → dull the senses, amaze"),
"stygian": ("adj", "Gk. Styx (river of the underworld)", "of the Styx → dark and dismal"),
"stymie": ("v", "from golf (a blocking ball)", "to block → hinder, thwart"),
"sublimate": ("v", "L. sublimare (to elevate)", "elevate/refine → channel into higher form"),
"subpoena": ("n", "L. sub poena (under penalty)", "appear 'under penalty' → a court summons"),
"subservient": ("adj", "sub- (under) + serv (serve)", "serving under → submissive, subordinate"),
"substantial": ("adj", "L. substantia (substance)", "having substance → considerable, solid"),
"summarily": ("adv", "L. summa (sum/total)", "in sum, at once → without delay"),
"sumptuous": ("adj", "L. sumptus (expense)", "lavishly expensive → luxurious"),
"supercilious": ("adj", "L. supercilium (eyebrow)", "raised eyebrow → haughtily contemptuous"),
"superficial": ("adj", "super- (above) + fic (face)", "on the surface → shallow"),
"superfluous": ("adj", "super- (over) + flu (flow)", "overflowing → more than needed"),
"supine": ("adj", "L. supinus (lying back)", "lying face-up → passive, unresisting"),
"supplant": ("v", "sub- + plant (sole of foot)", "trip up and take the place of → displace"),
"supplement": ("n", "sub- + ple (fill)", "fills under/adds → an addition"),
"supplicate": ("v", "sub- (under) + plic (fold/bend)", "bend the knee → beg humbly"),
"surfeit": ("n", "sur- (over) + L. fac (do)", "overdoing → an excess, glut"),
"surreptitious": ("adj", "sub- (secretly) + rapt (seized)", "secretly snatched → clandestine"),
"surrogate": ("n", "sub- + rog (ask/choose)", "chosen in place of → a substitute"),
"susceptible": ("adj", "sub- (up) + cept (take)", "easily taken in → impressionable, vulnerable"),
"suspend": ("v", "sub- (under) + pend (hang)", "hang up → halt temporarily"),
"swerve": ("v", "Old Eng. sweorfan (to scour/turn)", "veer off → turn abruptly"),
"synchronous": ("adj", "syn- (together) + chron (time)", "same time → simultaneous"),
"syncopated": ("adj", "Gk. synkope (a cutting short)", "cut short → shortened/off-beat"),
"synoptic": ("adj", "syn- (together) + opt (see)", "seeing the whole together → summarizing"),
"taciturn": ("adj", "L. tacere (to be silent)", "silent by nature → uncommunicative"),
"taint": ("v", "L. tingere (to dye/stain)", "stain → contaminate, cast doubt on"),
"tangible": ("adj", "L. tangere (to touch)", "touchable → having material substance"),
"tardy": ("adj", "L. tardus (slow)", "slow → late, delayed"),
"taut": ("adj", "Mid. Eng. toght (tight)", "pulled tight → tense"),
"tedium": ("n", "L. taedium (weariness)", "weariness → boredom"),
"teetotal": ("adj", "emphatic 'total' (t-total)", "totally abstaining from alcohol"),
"temerity": ("n", "L. temere (rashly)", "rashness → foolhardy boldness, nerve"),
"tendentious": ("adj", "L. tendere (to stretch/aim)", "aimed at a cause → biased, partisan"),
"tender": ("v", "L. tendere (to stretch/offer)", "stretch out → offer formally; also soft"),
"tentative": ("adj", "L. tentare (to try)", "a trial → provisional, unsettled"),
"tepid": ("adj", "L. tepere (to be lukewarm)", "lukewarm → unenthusiastic"),
"terse": ("adj", "L. tersus (polished/wiped)", "wiped clean → concise, to the point"),
"thrift": ("n", "Old Norse thrift (prosperity)", "careful prospering → economy in spending"),
"thwart": ("v", "Old Norse thvert (across/crosswise)", "go across → block, frustrate"),
"timorous": ("adj", "L. timor (fear)", "full of fear → timid"),
"toady": ("n", "from 'toad-eater' (quack's helper)", "a servile flatterer → a sycophant"),
"torrid": ("adj", "L. torrere (to parch/burn)", "burning hot → intensely passionate"),
"tout": ("v", "Old Eng. tutian (to peer/spy)", "loudly promote → advertise, praise"),
"toy": ("v", "from 'toy' (trifle)", "to trifle with → handle idly"),
"tranquil": ("adj", "L. tranquillus (calm)", "calm → free from agitation"),
"transgresion": ("n", "trans- (across) + gress (step)", "step across the line → a violation"),
"transitional": ("adj", "trans- (across) + it (go)", "going across → in passage between states"),
"treacherous": ("adj", "Fr. trichier (to cheat)", "cheating → disloyal; dangerously unstable"),
"tremulous": ("adj", "L. tremere (to tremble)", "trembling → quivering, timid"),
"trepidation": ("n", "L. trepidus (alarmed)", "trembling dread → alarm, anxiety"),
"truce": ("n", "Old Eng. treow (faith/pledge)", "a pledge → a halt to fighting"),
"tumult": ("n", "L. tumere (to swell)", "a swelling uproar → commotion"),
"turbid": ("adj", "L. turba (turmoil/crowd)", "stirred up → muddy, clouded"),
"turbulence": ("n", "L. turba (turmoil)", "stirred-up disorder → violent disturbance"),
"turgid": ("adj", "L. turgere (to swell)", "swollen → bombastic, inflated"),
"tyro": ("n", "L. tiro (recruit)", "a raw recruit → a beginner"),
"ulterior": ("adj", "L. ulterior (farther/beyond)", "lying beyond → hidden, concealed"),
"unalloyed": ("adj", "un- + alloy (mix)", "not mixed → pure, complete"),
"unconventional": ("adj", "un- + convention", "not by the usual rules → unorthodox"),
"uncouth": ("adj", "Old Eng. un-cuth (unknown)", "unfamiliar → crude, unrefined"),
"undergird": ("v", "under + gird (bind)", "bind from beneath → support, brace"),
"undermine": ("v", "under + mine (dig)", "dig under → weaken secretly"),
"underrate": ("v", "under + rate", "rate too low → underestimate"),
"underscore": ("v", "under + score (line)", "draw a line under → emphasize"),
"unearth": ("v", "un- + earth", "dig out of the earth → bring to light"),
"unexceptionable": ("adj", "un- + exception (objection)", "beyond objection → faultless, admirable"),
"unexceptional": ("adj", "un- + exceptional", "not exceptional → ordinary"),
"unflappable": ("adj", "un- + flap (panic)", "can't be flapped → imperturbable"),
"unmitigated": ("adj", "un- + mitigate (lessen)", "not lessened → utter, absolute"),
"unscathed": ("adj", "un- + scathe (harm)", "not harmed → unhurt"),
"unscrupulous": ("adj", "un- + scruple", "without scruples → unprincipled"),
"untenable": ("adj", "un- + L. tenere (to hold)", "can't be held/defended → indefensible"),
"untoward": ("adj", "un- + toward (favorable)", "not favorable → improper; unlucky"),
"upbraid": ("v", "Old Eng. upbregdan (to bring up against)", "throw up faults → reproach"),
"urbane": ("adj", "L. urbs (city)", "city-polished → suave, refined"),
"usurp": ("v", "L. usurpare (to seize)", "seize wrongfully → take by force"),
"usury": ("n", "L. usura (use/interest)", "charging for use → exorbitant interest"),
"vacuous": ("adj", "L. vacuus (empty)", "empty → showing no intelligence, blank"),
"vapid": ("adj", "L. vapidus (flat/spiritless)", "flat → dull, insipid"),
"variegated": ("adj", "L. varius (varied) + ag (drive)", "made varied → diverse, multicolored"),
"vegetate": ("v", "L. vegetare (to enliven; of plants)", "live like a plant → exist passively"),
"vehement": ("adj", "L. vehemens (eager/violent)", "forceful → passionate, intense"),
"venal": ("adj", "L. venum (sale)", "for sale → bribable, corrupt"),
"veneer": ("v", "Ger. furnieren (to furnish)", "a thin attractive layer → a deceptive surface"),
"verbiage": ("n", "L. verbum (word)", "excess of words → wordiness"),
"verdant": ("adj", "L. viridis (green)", "green → lush; (also) inexperienced"),
"verisimilar": ("adj", "L. veri (true) + simil (like)", "truth-like → appearing real"),
"veritable": ("adj", "L. veritas (truth)", "true → genuine, authentic"),
"vertigo": ("n", "L. vertere (to turn)", "a turning/whirling → dizziness"),
"vicious": ("adj", "L. vitium (vice/fault)", "full of vice → savage, malicious"),
"vigilant": ("adj", "L. vigil (awake/watchful)", "wakeful → carefully watchful"),
"violate": ("v", "L. violare (to do violence)", "do violence to → break, profane"),
"virulent": ("adj", "L. virus (poison)", "poisonous → exceedingly harmful, hostile"),
"vitiate": ("v", "L. vitium (fault)", "make faulty → spoil, corrupt"),
"vivid": ("adj", "L. vivere (to live)", "lifelike → bright, intensely clear"),
"voluptuary": ("n", "L. voluptas (pleasure)", "a pleasure-devotee → a sensualist"),
"voracious": ("adj", "L. vorare (to devour)", "devouring → ravenously greedy"),
"vulnerable": ("adj", "L. vulnus (wound)", "able to be wounded → open to harm"),
"waffle": ("v", "from 'waff' (to yap/waver)", "to waver → equivocate, be indecisive"),
"waft": ("v", "Du. wachten (to guard/convey)", "carried gently on air → float"),
"wag": ("n", "from 'waghalter' (joker)", "a witty joker → a wit"),
"waive": ("v", "Old Fr. weyver (to abandon)", "give up a claim → relinquish, defer"),
"wane": ("v", "Old Eng. wanian (to lessen)", "the moon wanes → decrease, decline"),
"wanton": ("adj", "Old Eng. wan- (lacking) + togen (trained)", "untrained → undisciplined; loose"),
"warrant": ("v", "Old Fr. warant (guarantee)", "to guarantee → justify, vouch for"),
"waver": ("v", "Old Eng. wafian (to fluctuate)", "sway to and fro → be irresolute"),
"wile": ("n", "Old Eng. wil (trick)", "a sly trick → a cunning stratagem"),
"wilful": ("adj", "will + -ful", "full of self-will → deliberate; stubborn"),
"winsome": ("adj", "Old Eng. wynn (joy) + -some", "full of joy → charming, engaging"),
"wither": ("v", "var. of 'weather'", "dry up → lose vigor, shrivel"),
"woeful": ("adj", "woe + -ful", "full of woe → wretched, deplorable"),
"xenophobe": ("n", "Gk. xenos (stranger) + phob (fear)", "fearer of strangers → a foreigner-hater"),
"yahoo": ("n", "the brutes in Swift's 'Gulliver'", "a coarse, uncouth person"),
"yield": ("v", "Old Eng. gieldan (to pay/produce)", "give forth → produce; give in"),
"yokel": ("n", "origin uncertain (poss. dialect)", "a country bumpkin → a rustic"),
"zealous": ("adj", "Gk. zelos (ardor)", "full of zeal → fervently devoted"),
"zeitgeist": ("n", "Ger. Zeit (time) + Geist (spirit)", "the spirit of the age"),
"zenith": ("n", "Arabic samt (path/overhead)", "the point overhead → the highest point"),
"zephyr": ("n", "Gk. Zephyros (west wind)", "the gentle west wind → a soft breeze"),
}
